server:
  port: 9090
  servlet:
    context-path: /rc
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:realcoding
    driver-class-name: org.h2.Driver
    username: sa
    password: null
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  main:
    allow-circular-references: true

mybatis:
  mapper-locations:
    - classpath:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

hibernate:
  dialect: org.hibernate.dialect.H2Dialect